# Generated by Django 3.2.9 on 2021-12-20 15:38

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_adm_levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('address_zip_code', models.CharField(max_length=5, validators=[apps.products.models.validate_zip_code], verbose_name='Zip code')),
                ('address_street', models.CharField(max_length=100, verbose_name='Street')),
                ('address_adm_level_1', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 1')),
                ('address_adm_level_2', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 2')),
                ('address_adm_level_3', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 3')),
                ('address_adm_level_4', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 4')),
                ('address_adm_level_5', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 5')),
                ('address_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_adm_levels.country', verbose_name='Country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producer', verbose_name='Producer')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchaseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceInCents', models.IntegerField(verbose_name='Price (cents)')),
                ('quantity', models.CharField(max_length=50, verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['priceInCents'],
                'unique_together': {('quantity', 'product')},
            },
        ),
    ]
