# Generated by Django 3.2.9 on 2022-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasteAndPurchaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Format: gg/mm/yyyy hh:mm', verbose_name='Event starts')),
                ('end_date', models.DateTimeField(help_text='Format: gg/mm/yyyy hh:mm', verbose_name='Event ends')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
