# Generated by Django 3.2.9 on 2022-01-06 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postal_address', '0002_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProducerOrderDeliveryAddress',
            fields=[
                ('postaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postal_address.postaladdress')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.producerorder')),
            ],
            bases=('postal_address.postaladdress',),
        ),
        migrations.CreateModel(
            name='OrderV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producerOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.producerorder')),
            ],
            options={
                'ordering': ['product', 'purchaseOption'],
            },
        ),
    ]
