# Generated by Django 3.2.9 on 2021-12-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priceByQuantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productpurchaseoption', verbose_name='Price by quantity'),
        ),
    ]
