# Generated by Django 3.2.9 on 2022-01-05 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderv2',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderv2',
            name='producerOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.producerorder'),
        ),
        migrations.AddField(
            model_name='orderv2',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='orderv2',
            name='purchaseOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productpurchaseoption'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='priceByQuantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productpurchaseoption', verbose_name='Price by quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='producerOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.producerorder'),
        ),
    ]
