# Generated by Django 3.2.9 on 2022-01-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderv2',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='orderv2',
            name='purchaseOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productpurchaseoption'),
        ),
    ]
