# Generated by Django 3.2.9 on 2022-01-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerorder',
            name='producer',
        ),
    ]
