# Generated by Django 3.2.9 on 2021-11-29 19:58
from django.contrib.auth.hashers import make_password
from django.db import migrations


def insert_data(apps, schema_editor):
    User = apps.get_model('users', 'User')

    user = User(id=None,
        username='example@example.com',
        email='example@example.com',
        nickname='Example',
        password=make_password('p4ssw0rd!'),
        is_active=True)
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
