# Generated by Django 3.2.9 on 2021-11-29 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('address_zip_code', localflavor.us.models.USZipCodeField(max_length=10, verbose_name='Zip code')),
                ('address_city', models.CharField(max_length=100, verbose_name='City')),
                ('address_state', localflavor.us.models.USStateField(max_length=2, verbose_name='State')),
                ('address_street', models.CharField(max_length=100, verbose_name='Street')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.producer', verbose_name='Producer')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TasteAndPurchaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Event starts')),
                ('end_date', models.DateTimeField(verbose_name='Event ends')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PriceByQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceInCents', models.IntegerField(verbose_name='Price (cents)')),
                ('quantity', models.CharField(max_length=50, verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['priceInCents'],
                'unique_together': {('quantity', 'product')},
            },
        ),
    ]
