# Generated by Django 3.2.9 on 2021-11-29 21:01
from django.db import migrations


def insert_data(apps, schema_editor):
    Producer = apps.get_model('events', 'Producer')
    Product = apps.get_model('events', 'Product')
    PriceByQuantity = apps.get_model('events', 'PriceByQuantity')

    producer = Producer(
        id=None, 
        name='Someone', 
        address_zip_code='36043',
        address_city='Montgomery',
        address_state='Alabama',
        address_street='Atchison Road')
    producer.save()

    product = Product(
        id=None,
        title='Food',
        description='Very interesting food',
        producer=producer
    )
    product.save()

    price_by_quantity = PriceByQuantity(
        id=None, 
        priceInCents=50,
        product=product, 
        quantity='Not much')
    price_by_quantity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
