# Generated by Django 3.2.9 on 2021-12-17 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasteandpurchaseevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
        ),
        migrations.AddField(
            model_name='tasteandpurchaseevent',
            name='products',
            field=models.ManyToManyField(to='products.Product', verbose_name='Products'),
        ),
    ]
