# Generated by Django 4.0.1 on 2022-01-10 17:26

from django.db import migrations, models
import django.db.models.deletion
import lib.postaladdress.validators


class Migration(migrations.Migration):

    dependencies = [
        ('postaladdress', '0002_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_code'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='postaladdress',
            options={'verbose_name': 'postal address', 'verbose_name_plural': 'postal addresses'},
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='adm_level_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='administrative level 1'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='adm_level_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='administrative level 2'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='adm_level_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='administrative level 3'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='adm_level_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='administrative level 4'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='adm_level_5',
            field=models.CharField(blank=True, max_length=100, verbose_name='administrative level 5'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postaladdress.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='street',
            field=models.CharField(max_length=100, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[lib.postaladdress.validators.validate_zip_code], verbose_name='zip code'),
        ),
    ]
