# Generated by Django 3.2.9 on 2021-12-20 16:38

from django.db import migrations, models
import django.db.models.deletion
import services.postal_address.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, validators=[services.postal_address.validators.validate_zip_code], verbose_name='Zip code')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('adm_level_1', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 1')),
                ('adm_level_2', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 2')),
                ('adm_level_3', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 3')),
                ('adm_level_4', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 4')),
                ('adm_level_5', models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 5')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postal_address.country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryAdminLevelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_level_1_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 1 Mandatory')),
                ('administrative_level_1_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 1 Endonym')),
                ('administrative_level_2_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 2 Mandatory')),
                ('administrative_level_2_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 2 Endonym')),
                ('administrative_level_3_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 3 Mandatory')),
                ('administrative_level_3_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 3 Endonym')),
                ('administrative_level_4_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 4 Mandatory')),
                ('administrative_level_4_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 4 Endonym')),
                ('administrative_level_5_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 5 Mandatory')),
                ('administrative_level_5_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 5 Endonym')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postal_address.country')),
            ],
            options={
                'ordering': ['country'],
            },
        ),
    ]
