# Generated by Django 3.2.9 on 2021-12-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Code')),
            ],
            options={
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='CountryAdminLevelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_level_1_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 1 Mandatory')),
                ('administrative_level_1_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 1 Endonym')),
                ('administrative_level_2_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 2 Mandatory')),
                ('administrative_level_2_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 2 Endonym')),
                ('administrative_level_3_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 3 Mandatory')),
                ('administrative_level_3_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 3 Endonym')),
                ('administrative_level_4_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 4 Mandatory')),
                ('administrative_level_4_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 4 Endonym')),
                ('administrative_level_5_mandatory', models.BooleanField(verbose_name='Adm. Lvl. 5 Mandatory')),
                ('administrative_level_5_endonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adm. Lvl. 5 Endonym')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_adm_levels.country', verbose_name='Country')),
            ],
            options={
                'ordering': ['country_code'],
            },
        ),
    ]
