# Generated by Django 4.0.1 on 2022-02-01 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=80, verbose_name='subject')),
                ('body', models.TextField(max_length=256, verbose_name='body')),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('send_email', models.BooleanField(default=False, verbose_name='also send email')),
                ('type', models.CharField(choices=[('EVENT', 'Event'), ('BIRTHDAY', 'Birthday')], default='EVENT', max_length=16, verbose_name='notification type')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='site.user', verbose_name='sender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.user', verbose_name='user notified')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
            },
        ),
    ]
