# Generated by Django 4.0.1 on 2022-02-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='origin',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='origin'),
        ),
    ]
