# Generated by Django 4.0.1 on 2022-02-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0002_notification_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='origin',
            field=models.CharField(default='SYSTEM', editable=False, max_length=50, verbose_name='origin'),
        ),
    ]
