# Generated by Django 4.0.1 on 2022-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0003_alter_notification_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='origin_object_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='origin object id'),
        ),
    ]
