# Generated by Django 4.0.1 on 2022-01-09 22:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postaladdress', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'produttore',
                'verbose_name_plural': 'produttori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProducerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ordine complessivo a produttore',
                'verbose_name_plural': 'ordini complessivi a produttore',
            },
        ),
        migrations.CreateModel(
            name='ProducerOrderDeliveryAddress',
            fields=[
                ('postaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postaladdress.postaladdress')),
            ],
            options={
                'verbose_name': 'indirizzo di consegna',
                'verbose_name_plural': 'indirizzi di consegna',
            },
            bases=('postaladdress.postaladdress',),
        ),
        migrations.CreateModel(
            name='ProducerPostalAddress',
            fields=[
                ('postaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postaladdress.postaladdress')),
            ],
            options={
                'verbose_name': 'indirizzo',
                'verbose_name_plural': 'indirizzi',
            },
            bases=('postaladdress.postaladdress',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='nome prodotto')),
                ('description', models.CharField(max_length=100, verbose_name='descrizione')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producer', verbose_name='produttore')),
            ],
            options={
                'verbose_name': 'prodotto',
                'verbose_name_plural': 'prodotti',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchaseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cents', models.IntegerField(verbose_name='prezzo EURO (cents)')),
                ('amount', models.CharField(max_length=50, verbose_name='quantità')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_option', to='products.product', verbose_name='prodotto')),
            ],
            options={
                'verbose_name': 'opzione di acquisto',
                'verbose_name_plural': 'opzioni di acquisto',
                'ordering': ['price_cents'],
                'unique_together': {('amount', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSED', 'Processed')], default='CREATED', max_length=10, verbose_name='stato ordine')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.user', verbose_name='ordinante')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.producer', verbose_name='produttore')),
                ('producer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.producerorder', verbose_name='ordine padre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.product', verbose_name='prodotto')),
                ('purchase_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.productpurchaseoption', verbose_name='opzione di acquisto')),
            ],
            options={
                'verbose_name': 'ordine semplice',
                'verbose_name_plural': 'ordini semplici',
                'ordering': ['purchase_option'],
            },
        ),
        migrations.AddField(
            model_name='producerorder',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='products.producerorderdeliveryaddress', verbose_name='indirizzo di consegna'),
        ),
        migrations.AddField(
            model_name='producerorder',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_order', to='products.producer', verbose_name='produttore'),
        ),
        migrations.AddField(
            model_name='producer',
            name='postal_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='products.producerpostaladdress', verbose_name='indirizzo'),
        ),
    ]
