# Generated by Django 4.0.1 on 2022-02-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='site.userprofile', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.producer', verbose_name='producer'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='producer_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.producerorder', verbose_name='in cumulative order'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='purchase_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.productpurchaseoption', verbose_name='purchase option'),
        ),
        migrations.AddField(
            model_name='product',
            name='added_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.userprofile', verbose_name='added by'),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producer', verbose_name='producer'),
        ),
        migrations.AddField(
            model_name='producerorder',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='products.producerorderdeliveryaddress', verbose_name='delivery address'),
        ),
        migrations.AddField(
            model_name='producerorder',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_order', to='products.producer', verbose_name='producer'),
        ),
        migrations.AddField(
            model_name='producer',
            name='added_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.userprofile', verbose_name='added by'),
        ),
        migrations.AddField(
            model_name='producer',
            name='postal_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='products.producerpostaladdress', verbose_name='postal address'),
        ),
        migrations.AlterUniqueTogether(
            name='productpurchaseoption',
            unique_together={('amount', 'product')},
        ),
    ]
