# Generated by Django 3.2.9 on 2021-11-29 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20211129_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('priceByQuantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.pricebyquantity', verbose_name='Price by quantity')),
            ],
            options={
                'ordering': ['priceByQuantity'],
            },
        ),
    ]
