# Generated by Django 4.0.1 on 2022-01-09 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Format: gg/mm/yyyy hh:mm', verbose_name='inizio evento')),
                ('end_date', models.DateTimeField(help_text='Format: gg/mm/yyyy hh:mm', verbose_name='fine evento')),
                ('title', models.CharField(max_length=50, verbose_name='titolo')),
                ('description', models.CharField(max_length=100, verbose_name='descrizione')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='organizzatore')),
                ('products', models.ManyToManyField(to='products.Product', verbose_name='prodotti')),
            ],
            options={
                'verbose_name': 'evento degustazione',
                'verbose_name_plural': 'eventi degustazione',
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
