# Generated by Django 4.0.1 on 2022-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Format: dd/mm/YYYY hh:mm', verbose_name='event start')),
                ('end_date', models.DateTimeField(help_text='Format: dd/mm/YYYY hh:mm', verbose_name='event end')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
            options={
                'verbose_name': 'taste event',
                'verbose_name_plural': 'taste events',
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
