# Generated by Django 4.0.1 on 2022-02-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site', '0001_initial'),
        ('events', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasteevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.userprofile', verbose_name='organizer'),
        ),
        migrations.AddField(
            model_name='tasteevent',
            name='products',
            field=models.ManyToManyField(to='products.Product', verbose_name='products'),
        ),
    ]
