# Generated by Django 4.0.1 on 2022-01-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
        ('products', '0002_alter_producer_options_alter_producerorder_options_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasteevent',
            options={'ordering': ['start_date', 'title'], 'verbose_name': 'taste event', 'verbose_name_plural': 'taste events'},
        ),
        migrations.AlterField(
            model_name='tasteevent',
            name='description',
            field=models.CharField(max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tasteevent',
            name='end_date',
            field=models.DateTimeField(help_text='Format: gg/mm/yyyy hh:mm', verbose_name='event end'),
        ),
        migrations.AlterField(
            model_name='tasteevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='organizer'),
        ),
        migrations.AlterField(
            model_name='tasteevent',
            name='products',
            field=models.ManyToManyField(to='products.Product', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='tasteevent',
            name='start_date',
            field=models.DateTimeField(help_text='Format: gg/mm/yyyy hh:mm', verbose_name='event start'),
        ),
        migrations.AlterField(
            model_name='tasteevent',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
