# Generated by Django 3.2.9 on 2021-12-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='address_adm_level_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 1'),
        ),
        migrations.AddField(
            model_name='producer',
            name='address_adm_level_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 2'),
        ),
        migrations.AddField(
            model_name='producer',
            name='address_adm_level_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 3'),
        ),
        migrations.AddField(
            model_name='producer',
            name='address_adm_level_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 4'),
        ),
        migrations.AddField(
            model_name='producer',
            name='address_adm_level_5',
            field=models.CharField(blank=True, max_length=100, verbose_name='Administrative Level 5'),
        ),
    ]
